# Generated by Django 3.0.8 on 2020-09-29 11:59

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_account_owner'),
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01000000000000000020816681711721685132943093776702880859375'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_payments_in', to='account.Account')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_payments_out', to='account.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_successful', models.BooleanField(default=True)),
                ('reason', models.CharField(max_length=255, null=True)),
                ('scheduled_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='scheduledpayment.ScheduledPayment')),
                ('transfer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='transfer.Transfer')),
            ],
        ),
    ]
